# Paper buffer

Here we categorize recent papers into several promising topics.

## Interpretability

- [Distribution-Guided Local Explanation for Black-box Classifiers](https://openreview.net/pdf?id=rJgFjREtwr), ICLR 2020.
- [Evaluation and Methods for Explanation through Robustness Analysis](https://openreview.net/pdf?id=Hye4KeSYDr), ICLR 2020.
- [Interpretable Network Structure for Modeling Contextual Dependency](https://openreview.net/pdf?id=BkgUB1SYPS), ICLR 2020.
- [Certifiably Robust Interpretation for Deep Learning](https://openreview.net/pdf?id=rkxVz1HKwB), ICLR 2020.

## Generalization and meta-learning

- [Towards Understanding Generalization in Gradient-Based Meta-Learning](https://openreview.net/pdf?id=SygT21SFvB), ICLR 2020.
- [Disentangling Trainability and Generalization in Deep Learning](https://openreview.net/pdf?id=Bkx1mxSKvB), ICLR 2020.
- [The Intriguing Role of Module Criticality in The Generalization of Deep Networks](https://openreview.net/pdf?id=S1e4jkSKvB), ICLR 2020.
- [Test-time Training For Out-of-Distribution Generalization](https://openreview.net/pdf?id=rJxbJeHFPS), ICLR 2020.
- [Entropy Penalty: Towards Generalization Beyond The IID Assumption](https://openreview.net/pdf?id=Byes0TNFDS), ICLR 2020.

## Curriculum learning

- [Dynamic Instance Hardness](https://openreview.net/pdf?id=H1lXVJStwB), ICLR 2020.
- [Curriculum Loss: Robust Learning and Generalization Against Labrl Corruption](https://openreview.net/pdf?id=rkgt0REKwS), ICLR 2020.
- [All Neural Networks Are Created Equally](https://openreview.net/pdf?id=HJgub1SKDH), ICLR 2020.

## Understanding intrinsic representation

- [Towards Interpreting Deep Neural Networks via Understanding Layer Behaviors](https://openreview.net/pdf?id=rkxMKerYwr), ICLR 2020.
- [Understanding and Improving Information Transfer in Multi-Task Learning](https://openreview.net/pdf?id=SylzhkBtDB), ICLR 2020.
- [Attention Interpretability Across NLP Tasks](https://openreview.net/pdf?id=BJe-_CNKPH), ICLR 2020.

## Data augmentation

- [Revisiting Self-Training for Neural Sequence Generation](https://openreview.net/pdf?id=SJgdnAVKDH), ICLR 2020.
- [Rethinking Data Augmentation: Self-supervision and Self-distillation](https://openreview.net/pdf?id=SkliR1SKDS), ICLR 2020.
- [Unsupervised Data Augmentation for Consistency Training](https://openreview.net/pdf?id=ByeL1R4FvS), ICLR 2020.
- [Meta Dropout: Learning to Perturb Latent Features For Generalization](https://openreview.net/pdf?id=BJgd81SYwr), ICLR 2020.
- [Implicit Semantic Data Augmentation for Deep Networks](https://arxiv.org/pdf/1909.12220.pdf), NeurIPS 2019.
- [When Covariate-Shifted Data Augmentation Increases Test Error And How To Fix It](https://openreview.net/pdf?id=ByxduJBtPB), ICLR 2020.
- [A Critical Analysis of Self-supervision, or What We Can Learn From A Single Image](https://openreview.net/pdf?id=B1esx6EYvr), ICLR 2020.

## Robustness

### Certified robustness

- [Robustness Verification for Transformers](https://openreview.net/pdf?id=BJxwPJHFwS), ICLR 2020.

### Adversarial examples

- [Fooling Pre-trained Language Models: An evolutionary approach to generate wrong sentences with high acceptability score](https://openreview.net/pdf?id=S1gV5gHKvB), ICLR 2020.
- [Pragmatic Evaluation of Adversarial Examples in Natural Language](https://openreview.net/pdf?id=BkxmKgHtwH), ICLR 2020.

## Compositionality

- [Towards Hierarchical Importance Attribution: Explaining Compositional Semantics for Neural Sequence Models](https://openreview.net/pdf?id=BkxRRkSKwr), ICLR 2020.
- [Measuring Compositional Generalization: A Comprehensive Method on Realistic Data](https://openreview.net/pdf?id=SygcCnNKwr), ICLR 2020.
- [What Can Neural Networks Reason About?](https://openreview.net/pdf?id=rJxbJeHFPS), ICLR 2020.

## Influence Function and Knowledge Tracing

- [Detecting Extrapolation with Local Ensembles](https://openreview.net/pdf?id=BJl6bANtwH), ICLR 2020.
- [Multi-stage Influence Function](https://openreview.net/pdf?id=r1geR1BKPr), ICLR 2020.
- [An Empirical and Comparative Analysis of Data Valuation with Scalable Algorithms](https://openreview.net/pdf?id=SygBIxSFDS), ICLR 2020.
- [Data Valuation Using Reinforcement Learning](https://arxiv.org/pdf/1909.11671.pdf), ICLR 2020.
- [Dataset Distillation](https://openreview.net/pdf?id=ryxO3gBtPB), ICLR 2020.


## Machine Translation

### Training

- [Connecting The Dots Between MLE and RL for Sequence Prediction](https://openreview.net/pdf?id=B1gX8JrYPr), ICLR 2020.

### Decoding

- [Neural Phrase-to-Phrase Machine Translation](https://openreview.net/pdf?id=S1gtclSFvr), ICLR 2020.
- [Masked Translation Model](https://openreview.net/pdf?id=HygaSxHYvH), ICLR 2020.
